[package]
name = "remote"
version = "0.0.1"
authors = ["Cubic6 <dev@cubic6.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { version = "4.0.0" }
serde = { version = "1.0.145" }
common = { path = "../common" }